Repository vishnuvnn/nmap-prometheus-exporter, pull requests merged in 2023-09, with the labels that each got.

#7 Feature: Alerting, Grafana dashboard
  README.md
  dashboard_template.json
Labels: enhancement

#8 Fix: Env var in docker compose file which controls frequency
  docker-compose.yml
Labels: bug

#9 Update docker-compose.yml
  docker-compose.yml
Labels: enhancement

#13 Improve Logging and Graceful Shutdown
  exporter.py
Labels: enhancement

#14 Feature: Azure support & Modularity
  Dockerfile
  README.md
  docker-compose.yml
  exporter.py
  modules/ip_fetcher.py
  modules/prometheus_format.py
  requirements.txt
Labels: documentation, enhancement
